package com.example.data.content

import com.example.data.model.AcquireContent
import com.example.data.model.Concept
import com.example.data.model.DefinitionItem
import com.example.data.model.PrimeContent
import com.example.data.model.RevisionTable
import com.example.data.model.Section

object Chapter3Content {
    val sections: List<Section> by lazy {
        listOf(
            Section(
                id = "3.1",
                chapterId = 3,
                number = "3.1",
                title = "Image Quality & Subject Contrast",
                printedPage = 49,
                pdfPage = 58,
                concepts = listOf(
                    Concept(
                        id = "3.1.1",
                        chapterId = 3,
                        sectionId = "3.1",
                        title = "Contrast, Spatial Resolution & Quantum Noise",
                        printedPage = 49,
                        pdfPage = 58,
                        prime = PrimeContent(
                            structuredNotes = listOf(
                                "Image quality has two basic descriptors: Contrast (ability to distinguish adjacent areas) and Spatial Resolution (ability to detect fine detail).",
                                "Subject contrast C = (u1 - u2) × t. Depends on structure thickness t and difference in linear attenuation coefficients (u1 - u2).",
                                "Contrast between bone (Z=13.3) and muscle (Z=7.4) is large at low kV (photoelectric effect Z^3), and drops significantly at high kV as Compton scattering predominates.",
                                "Contrast between fat (Z=6.4) and muscle is low and changes little with kV; contrast between air and soft tissue is due purely to density difference.",
                                "Positive contrast media: Iodine (Z=53, K-edge 33 keV) and Barium (Z=56, K-edge 37 keV) exploit high Z and photoelectric absorption.",
                                "Spatial resolution is quantified in line pairs per mm (lp/mm) using bar test patterns (e.g. 10 lp/mm resolves ~0.05 mm / 50 um detail).",
                                "Quantum mottle (noise) is generated by low photon numbers; relative noise = sqrt(M)/M = 1/sqrt(M). Signal-to-Noise Ratio (SNR) = M / sqrt(M) = sqrt(M)."
                            ),
                            keyConcepts = listOf("Subject Contrast", "Differential Attenuation", "Spatial Resolution (lp/mm)", "Quantum Mottle", "Signal-to-Noise Ratio (SNR)"),
                            definitions = listOf(
                                DefinitionItem("Subject Contrast", "The difference in X-ray intensity transmitted through a structure compared with adjacent tissue: C proportional to (u1 - u2) × t."),
                                DefinitionItem("Spatial Resolution", "The ability of an imaging system to resolve two separate high-contrast structures placed close together, expressed as line pairs per mm (lp/mm)."),
                                DefinitionItem("Quantum Mottle", "The statistical fluctuation in the number of X-ray photons absorbed per pixel, causing a grainy appearance.")
                            ),
                            equations = listOf(
                                "C proportional to (u1 - u2) × t",
                                "Smallest detail size approx 1 / (2 × lp/mm)",
                                "Relative Noise = 1 / sqrt(M)",
                                "SNR = sqrt(M)"
                            ),
                            tables = listOf(
                                RevisionTable(
                                    title = "Table 3.1: Photon Numbers, Noise and SNR",
                                    headers = listOf("Number of Events (M)", "Noise (sqrt(M))", "Noise (%)", "SNR"),
                                    rows = listOf(
                                        listOf("10", "3.16", "30%", "3:1"),
                                        listOf("100", "10", "10%", "10:1"),
                                        listOf("1,000", "31.6", "3.2%", "32:1"),
                                        listOf("10,000", "100", "1.0%", "100:1"),
                                        listOf("100,000", "316", "0.3%", "320:1")
                                    )
                                )
                            ),
                            whatYouMustUnderstand = listOf(
                                "To double the SNR, the number of absorbed photons (and thus patient dose) must be QUADRUPLED (4x).",
                                "Lower kV increases subject contrast for bone and iodine, but increases patient entrance surface dose because the beam is less penetrating."
                            ),
                            whatYouShouldMemorize = listOf(
                                "Iodine K-edge = 33 keV; Barium K-edge = 37 keV.",
                                "Film-screen requires ~3 uGy exit dose; fluoroscopy requires 0.2-0.5 uGy/s."
                            ),
                            highYieldFacts = listOf(
                                "Increasing mAs at constant kV increases photon count linearly, reducing relative noise and increasing SNR by sqrt(mAs).",
                                "Contrast between air and tissue does not drop significantly with kV because it is driven by density (Compton), not Z."
                            ),
                            chapterSummary = listOf(
                                "Subject contrast is determined by differential attenuation (u1-u2)t; image quality is fundamentally constrained by the trade-off between spatial resolution, contrast, and quantum noise."
                            ),
                            learningObjectives = listOf(
                                "Explain the physical basis of subject contrast and how kV influences tissue differentiation.",
                                "State the mathematical relationship between photon count, quantum noise, and SNR."
                            )
                        ),
                        acquire = AcquireContent(
                            simpleExplanation = "If you shine light through frosted glass with coins taped to it, the shadows of the coins are contrast. If you take a picture in very dim light with few photons, the grainy static is quantum noise.",
                            stepByStepMechanism = listOf(
                                "1. Incident uniform X-ray beam hits patient.",
                                "2. Bone absorbs photons strongly via Photoelectric effect; soft tissue transmits more photons.",
                                "3. Transmitted intensity pattern emerging from patient contains the subject contrast.",
                                "4. In low-dose areas (few photons detected), Poisson statistical fluctuation creates quantum mottle.",
                                "5. Increasing tube mAs delivers more photons per pixel, smoothing out the noise."
                            ),
                            whyItHappens = "Stochastic nature of photon emission and quantum absorption following Poisson statistics.",
                            clinicalRelevance = "In digital radiography and CT, increasing mAs reduces noise and improves low-contrast detectability (e.g. liver metastases), but increases patient dose.",
                            commonMisconception = "Misconception: Noise can be completely removed by post-processing without cost. Reality: Smoothing filters reduce noise but blur edges, sacrificing spatial resolution.",
                            analogy = "Listening to a weak radio station: turning up the volume (gain) only amplifies the static (quantum sink noise). You need a stronger radio transmission (more photons) for clear audio.",
                            imageQualityAndDoseImpact = "High kV reduces skin dose at the expense of lower subject contrast; contrast media (iodine/barium) restore contrast artificially.",
                            interactiveDiagramType = "CONTRAST_VS_KV"
                        )
                    )
                )
            ),
            Section(
                id = "3.4",
                chapterId = 3,
                number = "3.4",
                title = "Scattered Radiation & Grids",
                printedPage = 54,
                pdfPage = 63,
                concepts = listOf(
                    Concept(
                        id = "3.4.1",
                        chapterId = 3,
                        sectionId = "3.4",
                        title = "Scatter Reduction, Grid Ratio & Bucky Factor",
                        printedPage = 54,
                        pdfPage = 63,
                        prime = PrimeContent(
                            structuredNotes = listOf(
                                "Scattered radiation (S) obscures primary image-forming rays (P); scatter-to-primary ratio S/P is typically 4:1 for PA chest and 9:1 for lateral pelvis!",
                                "Scatter acts as a uniform veil, reducing contrast by factor (1 + S/P) up to 10-fold.",
                                "Methods to reduce scatter production: collimation (reducing field size) and compression (reducing patient thickness).",
                                "Antiscatter grid: thin lead strips (0.05-0.07 mm wide) separated by radiolucent interspace material (carbon fibre or aluminium).",
                                "Grid ratio = d / w (depth of channel divided by width). Typically 8:1 (thickness ~1.5 mm); high-ratio grids (12:1 to 16:1) used for high kV and large fields.",
                                "Line density: number of lead strips per cm (typically 30-80 strips/cm, standard 40 strips/cm).",
                                "Focused grid: lead strips tilted progressively to match beam divergence from the tube focus.",
                                "Grid cut-off occurs if focused grid is off-center, upside down, tilted, or outside its focal distance range.",
                                "Moving grid (Potter-Bucky): oscillates during exposure to blur lead strip shadows (grid lines).",
                                "Grid factor (Bucky factor): ratio of exposure with grid to exposure without grid (typically 3 to 5). Grids increase patient dose!"
                            ),
                            keyConcepts = listOf("Scatter-to-Primary Ratio (S/P)", "Grid Ratio (d/w)", "Focused Grid & Cut-off", "Moving Bucky Grid", "Grid Factor (Dose Penalty)"),
                            definitions = listOf(
                                DefinitionItem("Grid Ratio", "The ratio of the depth (height, d) of the lead strips to the width (w) of the interspace material: Grid Ratio = d / w."),
                                DefinitionItem("Grid Factor (Bucky Factor)", "The ratio of radiation exposure required with a grid to that required without a grid to achieve the same optical density (typically 3 to 5)."),
                                DefinitionItem("Contrast Improvement Factor", "The ratio of image contrast with a grid to image contrast without a grid (typically 2 to 4).")
                            ),
                            equations = listOf(
                                "Grid Ratio = d / w",
                                "Grid Factor = Exposure with grid / Exposure without grid (3 to 5)",
                                "Contrast reduction factor = 1 / (1 + S/P)"
                            ),
                            tables = listOf(
                                RevisionTable(
                                    title = "Grid Ratios and Clinical Applications",
                                    headers = listOf("Grid Ratio", "Acceptance Angle", "Selectivity", "Clinical Usage"),
                                    rows = listOf(
                                        listOf("No grid", "180 deg", "1", "Extremities, Paediatric imaging"),
                                        listOf("6:1", "Wide", "Moderate", "Mobile ward radiography (forgiving alignment)"),
                                        listOf("8:1", "Standard", "High", "General table Bucky, chest stands (up to 90 kV)"),
                                        listOf("12:1 to 16:1", "Narrow", "Very High", "High kV techniques (>100 kV), heavy patients")
                                    )
                                )
                            ),
                            whatYouMustUnderstand = listOf(
                                "Using a grid substantially improves contrast, but incurs a 3-5x dose penalty (Grid Factor).",
                                "An air gap (20-30 cm separation) allows obliquely scattered photons to miss the detector by inverse square law, acting as a grid alternative without lead lines."
                            ),
                            whatYouShouldMemorize = listOf(
                                "Standard grid ratio = 8:1; line density = 40 strips/cm.",
                                "Grid factor = 3 to 5.",
                                "Upside-down focused grid causes severe bilateral grid cut-off with only a central vertical strip exposed."
                            ),
                            highYieldFacts = listOf(
                                "In paediatric radiography, grids should NOT be used because thin infant anatomy generates very little scatter, sparing children unnecessary radiation dose.",
                                "Grid lines can cause moiré interference patterns on digital radiography receptors if line density is too low."
                            ),
                            chapterSummary = listOf(
                                "Compton scatter reduces contrast up to 10-fold; antiscatter grids absorb oblique scatter through high-ratio lead channels at the expense of a 3- to 5-fold dose increase."
                            ),
                            learningObjectives = listOf(
                                "Define grid ratio and explain how it influences scatter absorption and alignment tolerance.",
                                "Recognize causes of grid cut-off (off-center, off-distance, tilted, upside down)."
                            )
                        ),
                        acquire = AcquireContent(
                            simpleExplanation = "Think of a grid like venetian blinds. Direct X-rays coming straight from the tube slide right through the slats. Scattered X-rays bouncing sideways hit the lead slats and are stopped.",
                            stepByStepMechanism = listOf(
                                "1. Primary photons travel straight from focal spot towards image receptor.",
                                "2. Scattered photons bounce off patient tissues at random oblique angles.",
                                "3. Both reach the grid face.",
                                "4. Direct photons pass through the low-attenuation interspace channels.",
                                "5. Oblique scattered photons strike the lead strips and are absorbed.",
                                "6. The emerging beam has high primary content and dramatically reduced scatter veil."
                            ),
                            whyItHappens = "Geometric collimation of acceptance angles by high-aspect-ratio lead channels.",
                            clinicalRelevance = "Accidentally placing a focused grid upside down creates a black line down the center with completely blank white edges, necessitating a repeat exposure.",
                            commonMisconception = "Misconception: Grids reduce the amount of scatter produced in the patient. Reality: Grids have zero effect on scatter produced in the patient; they only stop scatter from reaching the detector. In fact, because mAs must increase 3-5x, the grid increases total scatter produced!",
                            analogy = "Wearing blinders on a racehorse: it blocks distracting sideways views while keeping forward vision clear.",
                            imageQualityAndDoseImpact = "Contrast improvement factor of 2 to 4, at the cost of a 3- to 5-fold increase in patient entrance skin dose.",
                            interactiveDiagramType = "GRID_SIMULATOR"
                        )
                    )
                )
            ),
            Section(
                id = "3.6",
                chapterId = 3,
                number = "3.6",
                title = "Unsharpness & X-ray Tube Physics",
                printedPage = 57,
                pdfPage = 66,
                concepts = listOf(
                    Concept(
                        id = "3.6.1",
                        chapterId = 3,
                        sectionId = "3.6",
                        title = "Geometric Blur, Line Focus & Heel Effect",
                        printedPage = 57,
                        pdfPage = 66,
                        prime = PrimeContent(
                            structuredNotes = listOf(
                                "Total unsharpness Ut combines three independent mechanisms: Ut = sqrt(Ug^2 + Um^2 + Us^2).",
                                "Geometric unsharpness: Ug = f × h / (F - h), where f = focal spot size, h = object-to-film distance, F = focus-to-film distance (FFD).",
                                "Movement unsharpness: Um = v × t (velocity × exposure time). Reduced by immobilization and short exposure times.",
                                "Line Focus Principle: target is angled (anode angle theta typically 7 to 20 deg). Actual focal spot is large (for heat loading); effective focal spot viewed from beam axis is small (for sharp resolution).",
                                "Rotating anode: bevelled molybdenum disc with tungsten-rhenium track rotating at 3000 rpm (50 Hz mains) or 9000 rpm (high-speed) driven by an induction motor.",
                                "Heat rating: for constant potential/3-phase, Heat (Joules) = kV × mAs. (Heat unit HU: 1.4 HU = 1 J).",
                                "Anode Heel Effect: X-rays produced beneath target surface are self-attenuated by the anode heel. Beam intensity is lower on the anode side and higher on the cathode side.",
                                "Clinical exploitation of heel effect: place thicker anatomy towards the cathode (e.g. chest wall in mammography, thoracic spine lower vertebrae towards cathode)."
                            ),
                            keyConcepts = listOf("Geometric Unsharpness Ug", "Line Focus Principle", "Anode Angle (7-20 deg)", "Rotating Anode & Heat Rating", "Anode Heel Effect"),
                            definitions = listOf(
                                DefinitionItem("Line Focus Principle", "The geometric principle of angling the anode target so the actual focal area for heat dissipation is large while the projected effective focal spot is small."),
                                DefinitionItem("Anode Heel Effect", "The reduction in X-ray beam intensity towards the anode side of the field caused by self-attenuation of X-rays within the target material."),
                                DefinitionItem("Geometric Unsharpness (Ug)", "The penumbral blurring of object edges caused by the non-zero dimensions of the X-ray tube focal spot.")
                            ),
                            equations = listOf(
                                "Ug = f × h / (F - h)",
                                "Ut = sqrt(Ug^2 + Um^2 + Us^2)",
                                "Effective Focal Spot = Actual Focal Spot × sin(theta)",
                                "Heat Loading (J) = kV × mAs (constant potential)"
                            ),
                            tables = listOf(
                                RevisionTable(
                                    title = "Typical Focal Spot Sizes in Diagnostic Radiology",
                                    headers = listOf("Modality / Application", "Fine Focus (mm)", "Broad Focus (mm)"),
                                    rows = listOf(
                                        listOf("General Radiography", "0.6 mm", "1.0 - 1.2 mm"),
                                        listOf("Mammography (contact)", "0.3 mm", "0.4 mm"),
                                        listOf("Mammography (magnification)", "0.1 mm", "0.15 mm"),
                                        listOf("Fluoroscopy", "0.6 mm", "1.0 mm"),
                                        listOf("Computed Tomography", "0.6 mm", "1.0 mm")
                                    )
                                )
                            ),
                            whatYouMustUnderstand = listOf(
                                "Decreasing anode angle decreases effective focal spot size (sharper image) and increases heat rating for a given spot size, BUT narrows the maximum useful field size.",
                                "The cathode side of the beam is more intense than the anode side. The anode should always point towards thinner anatomy."
                            ),
                            whatYouShouldMemorize = listOf(
                                "Anode angle is typically 7 to 20 degrees.",
                                "1.4 Heat Units (HU) = 1 Joule. Heat (J) = kV × mAs.",
                                "Rotating anode disc speeds: standard = 3000 rpm; high-speed = 9000 rpm."
                            ),
                            highYieldFacts = listOf(
                                "Focal spot blooming occurs at high mA and low kV because space charge weakens electron beam electrostatic focusing.",
                                "Molybdenum stem of the anode disk has low thermal conductivity to protect rotor bearings from heat seizure."
                            ),
                            chapterSummary = listOf(
                                "Image sharpness requires small focal spots and short exposures; line focus geometry and rotating anodes manage the immense heat (>99%) generated in X-ray production."
                            ),
                            learningObjectives = listOf(
                                "Calculate geometric unsharpness from focal spot size, object-to-detector distance, and FFD.",
                                "Explain the line focus principle, anode heel effect, and methods of anode cooling."
                            )
                        ),
                        acquire = AcquireContent(
                            simpleExplanation = "A tiny pinhead light makes crisp shadows; a large bulb makes blurry fuzzy edges (penumbra). To get a tiny focal spot that doesn't melt, we tilt the target so it looks like a narrow slit from below while spreading heat over a wide track.",
                            stepByStepMechanism = listOf(
                                "1. Electrons bombard the angled tungsten target (theta = 12 deg).",
                                "2. Heat is spread across a large physical track (e.g. 4.8 mm long).",
                                "3. Looking from the patient's perspective, the target is foreshortened into a 1.0 mm square (effective focal spot).",
                                "4. Because electrons penetrate into the target, X-rays emitted towards the anode must travel through more tungsten.",
                                "5. These anode-bound rays are attenuated (filtered), reducing beam intensity towards the anode edge (heel effect).",
                                "6. Cathode-bound rays exit with minimal target attenuation, making the cathode side up to 30% more intense."
                            ),
                            whyItHappens = "Target angle geometry and self-attenuation in dense tungsten (Z=74).",
                            clinicalRelevance = "In mammography, the cathode is placed over the chest wall where the breast is thickest, while the weaker anode side covers the thin nipple region.",
                            commonMisconception = "Misconception: The anode heel effect means the beam has higher energy on the cathode side. Reality: The anode side has lower intensity but a HIGHER mean energy (harder beam) because the target itself filtered out the soft X-rays!",
                            analogy = "Sundial penumbra: the sun is not a point source, so casting a shadow from high up creates a fuzzy penumbral edge.",
                            imageQualityAndDoseImpact = "Small focal spots eliminate geometric blur for fine microcalcifications in mammography, but limit allowable mA to prevent anode melting.",
                            interactiveDiagramType = "HEEL_EFFECT_SIM"
                        )
                    )
                )
            )
        )
    }
}
